import platform
import struct
import sys
import os
import requests
import serial.tools.list_ports
import re
import subprocess

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QTextCharFormat, QColor, QGuiApplication, QFont, QTextCursor
from PyQt6.QtWidgets import QGraphicsScene, QGraphicsPixmapItem, QTextEdit, QFileDialog, QMainWindow
from PyQt6.QtGui import QPixmap
from PyQt6.QtCore import pyqtSignal, QThread, Qt

from datetime import datetime

PROGRAMMER_MAJOR_VERSION = 1
PROGRAMMER_MINOR_VERSION = 2

class OBSCalibratorApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.finishSetup()
    def setupUi(self):
        self.setObjectName("obsCal")
        self.resize(490, 741)
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        self.setFont(font)
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 111, 641))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.ntu100Label = QtWidgets.QLabel(parent=self.frame_5)
        self.ntu100Label.setGeometry(QtCore.QRect(0, 0, 111, 20))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(12)
        self.ntu100Label.setFont(font)
        self.ntu100Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ntu100Label.setObjectName("ntu100Label")
        self.ntu100StartButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.ntu100StartButton.setGeometry(QtCore.QRect(0, 30, 111, 32))
        self.ntu100StartButton.setObjectName("ntu100StartButton")
        self.ntu100ResetButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.ntu100ResetButton.setGeometry(QtCore.QRect(0, 60, 111, 32))
        self.ntu100ResetButton.setObjectName("ntu100ResetButton")
        self.ntu100AverageLabel = QtWidgets.QLabel(parent=self.frame_5)
        self.ntu100AverageLabel.setGeometry(QtCore.QRect(0, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(12)
        self.ntu100AverageLabel.setFont(font)
        self.ntu100AverageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ntu100AverageLabel.setObjectName("ntu100AverageLabel")
        self.ntu100AverageSpinBox = QtWidgets.QDoubleSpinBox(parent=self.frame_5)
        self.ntu100AverageSpinBox.setGeometry(QtCore.QRect(0, 120, 111, 21))
        self.ntu100AverageSpinBox.setReadOnly(True)
        self.ntu100AverageSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.ntu100AverageSpinBox.setMaximum(65536.0)
        self.ntu100AverageSpinBox.setObjectName("ntu100AverageSpinBox")
        self.ntu100TextEdit = QtWidgets.QTextEdit(parent=self.frame_5)
        self.ntu100TextEdit.setGeometry(QtCore.QRect(5, 150, 101, 489))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.ntu100TextEdit.setFont(font)
        self.ntu100TextEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.FixedColumnWidth)
        self.ntu100TextEdit.setReadOnly(True)
        self.ntu100TextEdit.setObjectName("ntu100TextEdit")
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(130, 10, 111, 641))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.ntu250TextEdit = QtWidgets.QTextEdit(parent=self.frame_4)
        self.ntu250TextEdit.setGeometry(QtCore.QRect(4, 150, 101, 489))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.ntu250TextEdit.setFont(font)
        self.ntu250TextEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.FixedColumnWidth)
        self.ntu250TextEdit.setReadOnly(True)
        self.ntu250TextEdit.setObjectName("ntu250TextEdit")
        self.ntu250AverageSpinBox = QtWidgets.QDoubleSpinBox(parent=self.frame_4)
        self.ntu250AverageSpinBox.setGeometry(QtCore.QRect(0, 120, 111, 21))
        self.ntu250AverageSpinBox.setReadOnly(True)
        self.ntu250AverageSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.ntu250AverageSpinBox.setMaximum(65536.0)
        self.ntu250AverageSpinBox.setObjectName("ntu250AverageSpinBox")
        self.ntu250AverageLabel = QtWidgets.QLabel(parent=self.frame_4)
        self.ntu250AverageLabel.setGeometry(QtCore.QRect(0, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(12)
        self.ntu250AverageLabel.setFont(font)
        self.ntu250AverageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ntu250AverageLabel.setObjectName("ntu250AverageLabel")
        self.ntu250ResetButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.ntu250ResetButton.setGeometry(QtCore.QRect(1, 60, 111, 32))
        self.ntu250ResetButton.setObjectName("ntu250ResetButton")
        self.ntu250StartButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.ntu250StartButton.setGeometry(QtCore.QRect(1, 30, 111, 32))
        self.ntu250StartButton.setObjectName("ntu250StartButton")
        self.ntu250Label = QtWidgets.QLabel(parent=self.frame_4)
        self.ntu250Label.setGeometry(QtCore.QRect(1, 0, 111, 20))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(12)
        self.ntu250Label.setFont(font)
        self.ntu250Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ntu250Label.setObjectName("ntu250Label")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(250, 10, 111, 641))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.ntu500Label = QtWidgets.QLabel(parent=self.frame_3)
        self.ntu500Label.setGeometry(QtCore.QRect(0, 0, 111, 21))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(12)
        self.ntu500Label.setFont(font)
        self.ntu500Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ntu500Label.setObjectName("ntu500Label")
        self.ntu500StartButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.ntu500StartButton.setGeometry(QtCore.QRect(0, 30, 111, 32))
        self.ntu500StartButton.setObjectName("ntu500StartButton")
        self.ntu500ResetButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.ntu500ResetButton.setGeometry(QtCore.QRect(0, 60, 111, 32))
        self.ntu500ResetButton.setObjectName("ntu500ResetButton")
        self.ntu500AverageLabel = QtWidgets.QLabel(parent=self.frame_3)
        self.ntu500AverageLabel.setGeometry(QtCore.QRect(0, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(12)
        self.ntu500AverageLabel.setFont(font)
        self.ntu500AverageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ntu500AverageLabel.setObjectName("ntu500AverageLabel")
        self.ntu500AverageSpinBox = QtWidgets.QDoubleSpinBox(parent=self.frame_3)
        self.ntu500AverageSpinBox.setGeometry(QtCore.QRect(0, 120, 111, 21))
        self.ntu500AverageSpinBox.setReadOnly(True)
        self.ntu500AverageSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.ntu500AverageSpinBox.setMaximum(65536.0)
        self.ntu500AverageSpinBox.setObjectName("ntu500AverageSpinBox")
        self.ntu500TextEdit = QtWidgets.QTextEdit(parent=self.frame_3)
        self.ntu500TextEdit.setGeometry(QtCore.QRect(5, 150, 101, 489))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.ntu500TextEdit.setFont(font)
        self.ntu500TextEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.FixedColumnWidth)
        self.ntu500TextEdit.setReadOnly(True)
        self.ntu500TextEdit.setObjectName("ntu500TextEdit")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(370, 10, 111, 641))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ntu1000Label = QtWidgets.QLabel(parent=self.frame_2)
        self.ntu1000Label.setGeometry(QtCore.QRect(0, 0, 111, 21))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(12)
        self.ntu1000Label.setFont(font)
        self.ntu1000Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ntu1000Label.setObjectName("ntu1000Label")
        self.ntu1000StartButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.ntu1000StartButton.setGeometry(QtCore.QRect(0, 30, 111, 32))
        self.ntu1000StartButton.setObjectName("ntu1000StartButton")
        self.ntu1000ResetButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.ntu1000ResetButton.setGeometry(QtCore.QRect(0, 60, 111, 32))
        self.ntu1000ResetButton.setObjectName("ntu1000ResetButton")
        self.ntu1000AverageLabel = QtWidgets.QLabel(parent=self.frame_2)
        self.ntu1000AverageLabel.setGeometry(QtCore.QRect(0, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(12)
        self.ntu1000AverageLabel.setFont(font)
        self.ntu1000AverageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ntu1000AverageLabel.setObjectName("ntu1000AverageLabel")
        self.ntu1000AverageSpinBox = QtWidgets.QDoubleSpinBox(parent=self.frame_2)
        self.ntu1000AverageSpinBox.setGeometry(QtCore.QRect(0, 120, 111, 21))
        self.ntu1000AverageSpinBox.setReadOnly(True)
        self.ntu1000AverageSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.ntu1000AverageSpinBox.setMaximum(65536.0)
        self.ntu1000AverageSpinBox.setObjectName("ntu1000AverageSpinBox")
        self.ntu1000TextEdit = QtWidgets.QTextEdit(parent=self.frame_2)
        self.ntu1000TextEdit.setGeometry(QtCore.QRect(6, 150, 101, 489))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.ntu1000TextEdit.setFont(font)
        self.ntu1000TextEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.FixedColumnWidth)
        self.ntu1000TextEdit.setReadOnly(True)
        self.ntu1000TextEdit.setObjectName("ntu1000TextEdit")
        self.findEquationButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.findEquationButton.setGeometry(QtCore.QRect(10, 660, 101, 32))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(11)
        self.findEquationButton.setFont(font)
        self.findEquationButton.setObjectName("findEquationButton")
        self.equationLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.equationLineEdit.setGeometry(QtCore.QRect(120, 660, 361, 31))
        self.equationLineEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.equationLineEdit.setFont(font)
        self.equationLineEdit.setObjectName("equationLineEdit")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 24))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar()
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("obsCal", "OBS Calibration"))
        self.ntu100Label.setText(_translate("obsCal", "100 NTU"))
        self.ntu100StartButton.setText(_translate("obsCal", "Start"))
        self.ntu100ResetButton.setText(_translate("obsCal", "Reset"))
        self.ntu100AverageLabel.setText(_translate("obsCal", "Average"))
        self.ntu100TextEdit.setPlaceholderText(_translate("obsCal", "Samples will appear here as they are taken."))
        self.ntu250TextEdit.setPlaceholderText(_translate("obsCal", "1                      2                      3                      4                      5                      6                      7                      8                      9                      10                      11                      12                      13                      14                      15                      16                      17                      18                      19                      20                      21                      22                      23                      24                      25                      26                      27                      28                      29                      30                     "))
        self.ntu250AverageLabel.setText(_translate("obsCal", "Average"))
        self.ntu250ResetButton.setText(_translate("obsCal", "Reset"))
        self.ntu250StartButton.setText(_translate("obsCal", "Start"))
        self.ntu250Label.setText(_translate("obsCal", "250 NTU"))
        self.ntu500Label.setText(_translate("obsCal", "500 NTU"))
        self.ntu500StartButton.setText(_translate("obsCal", "Start"))
        self.ntu500ResetButton.setText(_translate("obsCal", "Reset"))
        self.ntu500AverageLabel.setText(_translate("obsCal", "Average"))
        self.ntu500TextEdit.setPlaceholderText(_translate("obsCal", "1                      2                      3                      4                      5                      6                      7                      8                      9                      10                      11                      12                      13                      14                      15                      16                      17                      18                      19                      20                      21                      22                      23                      24                      25                      26                      27                      28                      29                      30                     "))
        self.ntu1000Label.setText(_translate("obsCal", "1000 NTU"))
        self.ntu1000StartButton.setText(_translate("obsCal", "Start"))
        self.ntu1000ResetButton.setText(_translate("obsCal", "Reset"))
        self.ntu1000AverageLabel.setText(_translate("obsCal", "Average"))
        self.ntu1000TextEdit.setPlaceholderText(_translate("obsCal", "1                      2                      3                      4                      5                      6                      7                      8                      9                      10                      11                      12                      13                      14                      15                      16                      17                      18                      19                      20                      21                      22                      23                      24                      25                      26                      27                      28                      29                      30                     "))
        self.findEquationButton.setText(_translate("obsCal", "Find Equation"))
        self.equationLineEdit.setText(_translate("obsCal", "Best Fit Equation: "))

    def finishSetup(self):
        self.ntu100ResetButton.setDisabled(True)
        self.ntu250ResetButton.setDisabled(True)
        self.ntu500ResetButton.setDisabled(True)
        self.ntu1000ResetButton.setDisabled(True)

        self.connectUIElements()

    def connectUIElements(self):
        self.ntu100StartButton.clicked.connect(lambda: self.startButtonClicked(100))
        self.ntu250StartButton.clicked.connect(lambda: self.startButtonClicked(250))
        self.ntu500StartButton.clicked.connect(lambda: self.startButtonClicked(500))
        self.ntu1000StartButton.clicked.connect(lambda: self.startButtonClicked(1000))

        self.ntu100ResetButton.clicked.connect(lambda: self.resetButtonClicked(100))
        self.ntu250ResetButton.clicked.connect(lambda: self.resetButtonClicked(250))
        self.ntu500ResetButton.clicked.connect(lambda: self.resetButtonClicked(500))
        self.ntu1000ResetButton.clicked.connect(lambda: self.resetButtonClicked(1000))

    def startButtonClicked(self, ntu):
        match ntu:
            case 100:
                self.ntu100ResetButton.setEnabled(True)
                self.ntu100StartButton.setDisabled(True)
            case 250:
                self.ntu250ResetButton.setEnabled(True)
                self.ntu250StartButton.setDisabled(True)
            case 500:
                self.ntu500ResetButton.setEnabled(True)
                self.ntu500StartButton.setDisabled(True)
            case 1000:
                self.ntu1000ResetButton.setEnabled(True)
                self.ntu1000StartButton.setDisabled(True)
            case _:
                pass

    def resetButtonClicked(self, ntu):
        match ntu:
            case 100:
                self.ntu100ResetButton.setDisabled(True)
                self.ntu100StartButton.setEnabled(True)
            case 250:
                self.ntu250ResetButton.setDisabled(True)
                self.ntu250StartButton.setEnabled(True)
            case 500:
                self.ntu500ResetButton.setDisabled(True)
                self.ntu500StartButton.setEnabled(True)
            case 1000:
                self.ntu1000ResetButton.setDisabled(True)
                self.ntu1000StartButton.setEnabled(True)
            case _:
                pass


def main():
    app = QtWidgets.QApplication(sys.argv)

    obsCalibrator = OBSCalibratorApp()
    obsCalibrator.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()